feature#134A
arec0000/summer-school-back pull request #3
Opened 2023-03-10 10:21 UTC by Rus8921

2023-03-10 10:21 UTC, Vaziakozia approved these changes

2023-03-10 12:51 UTC, Yitwaaien commented
В задаче сказано создать сущность Course. Помни про принцип атомарности, одна задача - одна ветка. Сейчас в одном коммите ты создаешь несколько сущностей

2023-03-10 14:21 UTC, Yitwaaien requested changes
Все здорово! Функционал рабочий, добавил много сущностей, есть несколько моментов, типо лишних строк/не совсем понятной связи, иногда неверного нейминга, и файлов недобавленных в игнор. Но это ничего страшного, это мелочи

2023-03-10 14:21 UTC, Yitwaaien commented on src/Entity/Entity/Course/Course.php
> +     * @var \DateTimeInterface|null Star Date of course
Start Date,  понимаю стремление к документированию своего кода, но тут это кажется избыточным. Свойство startDate и так выглядит понятным

2023-03-10 14:21 UTC, Yitwaaien commented on src/Entity/Entity/Teachers/Teachers.php
> +    public function __construct()
Функцию construct стоит выносить до объявления свойств, так принято

2023-03-10 14:21 UTC, Yitwaaien commented on src/Entity/Entity/feedback/Feedback.php
> +    // Аннотации для того чтобы свойство класса стало атрибутом в бд
удалить

2023-03-10 14:21 UTC, Yitwaaien commented on src/Entity/Entity/feedback/Feedback.php
> +    /** @var string|null text of feedback */
лучше просто text и так понятно к какой сущности относится это поле

2023-03-10 14:21 UTC, Yitwaaien commented on .idea/php.xml
> +<project version="4">
Этот файл не должен попадать в репозиторий, добавь его в gitignore

2023-03-10 14:21 UTC, Yitwaaien commented on .idea/modules.xml
> +  <component name="ProjectModuleManager">
Кажется, этот файл тоже не должен попадать в репозиторий, добавь в игнор

2023-03-10 14:21 UTC, Yitwaaien commented on .idea/summer-school-back.iml
> +<module type="WEB_MODULE" version="4">
Это точно не должно попадать в репозиторий, добавь в игнор

2023-03-10 14:21 UTC, Yitwaaien commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
добавь в игнор

2023-03-11 11:55 UTC, IlyaLis1 approved these changes

2023-03-11 12:02 UTC, arec0000 approved these changes

2023-03-11 12:03 UTC, merged